global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '${SMTP_FROM_ADDRESS}'
  smtp_auth_username: '${SMTP_USER}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

route:
  receiver: 'email-and-discord'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: 'email-and-discord'
    email_configs:
      - to: '${SMTP_USER}'
        send_resolved: true
    webhook_configs:
      - url: 'http://alertmanager-discord:8080/alert'
        send_resolved: true
